name: "Free GPU Test"
author: "lvyufeng"
description: "Automatically test integration/gpu tests against Kaggle notebook with GPU runtime"
inputs:
  kaggle_username:
    description: "Kaggle user name for pushing tests"
    required: true
  kaggle_key:
    description: "Kaggle API key for pushing tests"
    required: true
  kernel_name:
    description: "Name of Kaggle kernel"
    required: true
  kernel_job_file:
    description: "Task file of Kaggle kernel"
    required: true

outputs:
  automatic_releases_tag:
    description: "The release tag this action just processed"
    value: ""
  upload_url:
    description: "The URL for uploading additional assets to the release"
    value: ""
runs:
  using: "composite"
  
  steps:
  - name: install-kaggle-cli
    shell: bash
    env:
      KAGGLE_KEY: ${{ inputs.kaggle_key }}
      KAGGLE_USERNAME: ${{ inputs.kaggle_username }}
    run: |
      cd ~
      mkdir .kaggle
      python -m pip install --upgrade kaggle --user
      python ${{ github.action_path }}/utils/dump_kaggle_json.py
      chmod 600 /home/runner/.kaggle/kaggle.json

  - name: send tests
    shell: bash
    env:
      KERNEL_NAME: ${{ inputs.kernel_name }}
      KERNEL_JOB_FILE: ${{ github.workspace }}/${{ inputs.kernel_job_file }}
    run: |
      kaggle kernels init -p ${{ github.action_path }}
      cd ${{ github.action_path }}
      python utils/prepare_job.py
      kaggle kernels push

  - name: check job status
    shell: bash
    env:
      KERNEL_NAME: ${{ inputs.kernel_name }}
    run: |
      cd ${{ github.action_path }}
      python utils/check_status.py
      
branding:
  icon: activity
  color: green
